### PR TITLE
Build with vtk89

### PR DESCRIPTION
**Pull request by cpinter**
This branch is the continuation of the work of @lassoan in PR https://github.com/Slicer/Slicer/pull/1252

Python wrapping of VTK classes seems to work. The remaining errors on Windows are:
```
"c:\e\ScD\Slicer-build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\e\ScD\Slicer-build\E\DataStore\DataStore\Testing\Cxx\qSlicerDataStoreModuleCxxTests.vcxproj" (default target) (290) ->
(ClCompile target) ->
  C:\e\ScD\Slicer-build\E\DataStore\DataStore\Testing\Cxx\qSlicerDataStoreModuleCxxTests.cxx(139): error C2039: 'SendToStdErrOn': is not a member of 'vtkWin32OutputWindow' [C:\e\ScD\Slicer-build\E\DataStore\DataStore\Testing\Cxx\qSlicerDataStoreModuleCxxTests.vcxproj]


"c:\e\ScD\Slicer-build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\e\ScD\Slicer-build\Modules\Loadable\Segmentations\Logic\vtkSlicerSegmentationsModuleLogicPython.vcxproj" (default target) (518) ->
"C:\e\ScD\Slicer-build\Modules\Loadable\Segmentations\Logic\vtkSlicerSegmentationsModuleLogicPythonD.vcxproj" (default target) (519) ->
  C:\e\ScD\Slicer-build\Modules\Loadable\Segmentations\Logic\vtkImageGrowCutSegmentPython.cxx(195): error C2280: 'vtkImageGrowCutSegment::vtkImageGrowCutSegment(const vtkImageGrowCutSegment &)': attempting to reference a deleted function [C:\e\ScD\Slicer-build\Modules\Loadable\Segmentations\Logic\vtkSlicerSegmentationsModuleLogicPythonD.vcxproj]
```

The first error should not happen, as the precompiler directive of
`#if VTK_MAJOR_VERSION >= 9 || (VTK_MAJOR_VERSION >= 8 && VTK_MINOR_VERSION >= 90)`
should work (see line in question in generated file [here](https://gist.github.com/cpinter/29b3244c8a4a63390c8b9fe837d389ba#file-qslicerdatastoremodulecxxtests-cxx-L137)). Maybe the VTK version variables are not propagated to the project. correctly

In the case of the second error, the python wrapping C++ file is quite different. In the current Slicer master, vtkImageGrowCutSegmentPython.cxx does not contain a PyvtkImageGrowCutSegment_vtkImageGrowCutSegment ragular constructor, but a VTK constructor PyvtkImageGrowCutSegment_NewInstance instead. It is possible that the class is not wrapped as a VTK class.

### CODE REVIEW

**Comment by cpinter** [comment]
One more thing: Slicer.exe is built, but on launch I'm getting this:
image

**Comment by lassoan** [comment]
Does python37.dll exists? Do you see more information if you start from the debugger? Do you see any additional information in Windows event log?

**Comment by jcfr** [comment]
> python37.dll

Slicer is expected to link against python36. See https://github.com/Slicer/Slicer/blob/ba6e736fba521d4a5d653af03b204add643f793a/SuperBuild/External_python.cmake#L60

@cpinter During the project week, did we find out the root cause of this ?

**Comment by jcfr** [comment]
Looks like the changes requiring `Python3_*` variables to be passed are missing. When I land, I will check  if these changes where done on my other laptop.

**Comment by jcfr** [comment]
Looks like the changes requiring `Python3_*` variables to be passed are missing. When I land, I will check  if these changes where done on my other laptop.

**Comment by pieper** [comment]
Let me know if/when you'd like me to try a mac build.

**Comment by cpinter** [comment]
Sorry for the delay... I'm back now.

@jcfr Have you had time to check on your other laptop regarding passing the `Python3_*` variables?

**Comment by jcfr** [comment]
> Have you had time to check on your other laptop regarding passing the Python3_* variables?

Sadly, I can't find the changes on my laptop.

**Comment by cpinter** [comment]
Thanks for the info, @jcfr!

If anyone has an idea about how to address any of the three issues (1. wrong VTK version in ifdef, 2. wrong python wrapping of VTK class, 3. python37.dll issue), feel free to issue a new PR or just comment here. I'll work on other things now, but can test ideas using my build.

**Comment by lassoan** [comment]
> The first error should not happen, as the precompiler directive of
#if VTK_MAJOR_VERSION >= 9 || (VTK_MAJOR_VERSION >= 8 && VTK_MINOR_VERSION >= 90)
should work (see line in question in generated file here). Maybe the VTK version variables are not propagated to the project. correctly

You need to add:

    #include <vtkVersion.h> // must precede reference to VTK_MAJOR_VERSION

**Comment by jcfr** [comment]
Closing. This PR is superseded by https://github.com/Slicer/Slicer/pull/5141

**Pull request closed without merging**
