### PR TITLE
ENH: Update VTK to latest master (WIP)

### PR DESCRIPTION
**Pull request by lassoan**
This is a work in progress, just created the pull request to give better visibility and allow all maintainers to make changes directly in this branch.

### CODE REVIEW

**Comment by cpinter** [comment]
Branch that fixes the CTK error about not finding python36.lib
https://github.com/cpinter/CTK/tree/build-with-vtk89

**Comment by cpinter** [comment]
Superseded by https://github.com/Slicer/Slicer/pull/1312

**Comment by lassoan** [comment]
> Superseded by #1312

Should we close this PR then?

Note that since the lassoan:build-with-vtk89 branch is in a pull request, you can push to this branch in my fork directly. So, you can you don't have to create a new PR just to be able to push changes. Of course, if you prefer to create a new PR for any other reason, then I'm OK with it.

**Comment by jcfr** [comment]
Closing. This branch was superseded by https://github.com/Slicer/SlicerGitSVNArchive/pull/1312

**Pull request closed without merging**
