### PR TITLE
BUG: Change invocation of ImageDataModifiedEvent to a CustomModifiedEvent

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
When calling StartModify(), ImageDataModifiedEvent was still invoked through InvokeEvent.

This changes the invocation to InvokeCustomModifiedEvent, pausing the event until EndModify() is called.

@lassoan

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution :+1: The change looks reasonable.

Could you also remove the comment mentioning `ImageDataModifiedEvent` in `Libs/MRML/Core/vtkMRMLDoubleArrayNode.cxx` ?

**Comment by Sunderlandkyl** [comment]
@jcfr Sure, done!

**Review by lassoan — COMMENTED** [review]
Looks good, thank you!

Is Start/End Modify tested in the image data modified test? If not, could you add a few lines there to make sure it works correctly now and in the future?

**Comment by Sunderlandkyl** [comment]
They were not. I've added some code to test both StartModify and EndModify in vtkMRMLVolumeNodeEventsTest.

**Comment by Sunderlandkyl** [comment]
Also, vtkMRMLVolumeNodeEventsTest is not added to ctest.  (simple_test is never called in CMakeLists.txt).
Is this intentional?

**Comment by jcfr** [comment]
> Also, vtkMRMLVolumeNodeEventsTest is not added to ctest (simple_test is never called with vtkMRMLVolumeNodeEventsTest in CMakeLists.txt).
Is this intentional?

Good catch. No, it should definitively be added as a test.

**Comment by jcfr** [comment]
For reference, test was originally added in https://github.com/Slicer/Slicer/commit/2cd8b8dd4f26c824a1f4d80996a149e848fc526d

**Comment by Sunderlandkyl** [comment]
OK, the test has been added.

**Comment by lassoan** [comment]
Perfect, thank you!

**Comment by Sunderlandkyl** [comment]
Any other changes required here?

**Comment by lassoan** [comment]
Thank you, it's [merged](https://github.com/Slicer/Slicer/commit/fe66aa781a8ab170c63bcd4d93150b37c9443b6c).

**Pull request closed without merging**
