### PR TITLE
ENH: Add vtkMRMLStorageNode::GetStorableNode() method

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
See discussion here: https://discourse.slicer.org/t/no-getstorablenode-method-in-vtkmrmlstoragenode/4764/2

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
There are some build errors in CircleCI, which may be valid, but other than that it looks good to me. Thank you!

**Comment by Sunderlandkyl** [comment]
@lassoan Fixed.

**Comment by Sunderlandkyl** [comment]
@lassoan

**Comment by lassoan** [comment]
Looks good, thank you! Merging it now.

**Comment by lassoan** [comment]
Committed r27593. Thank you!

**Pull request closed without merging**
