### PR TITLE
ENH: Standardize how JsonCpp config is managed

### PR DESCRIPTION
**Pull request by jcfr**
For consistency the JsonCpp variables passed to the projects were changed
to JsonCpp_INCLUDE_DIR and JsonCpp_LIBRARY.

JsonCpp_DIR should be used for project providing a Config module.

$ git shortlog 9a74e80ac..8692b09b6 --no-merges
Johan Andruejol (1):
      ENH: Uniformize the use of JsonCpp with VTK

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @vovythevov

**Comment by vovythevov** [comment]
@jcfr: Thanks ! This should wait that https://github.com/Slicer/SlicerExecutionModel/issues/81 is solved though, otherwise there are going to be build errors when building without Slicer_BUILD_PARAMETERSERIALIZER_SUPPORT.

**Comment by vovythevov** [comment]
@jcfr: I suggest we use this commit instead https://github.com/vovythevov/Slicer/commit/02213724755e9a0e12ae6f5b31116b6f6e3bba48, it includes the fix in SlicerExecutionModel

**Comment by jcfr** [comment]
Yeap. Please, consider updating the PR.

**Comment by jcfr** [comment]
LGTM. Please, integrate :+1:

**Comment by vovythevov** [comment]
Integrated in [r25346](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25346)

**Comment by jcfr** [comment]
SlicerDocker image rebuild in progress

**Pull request closed without merging**
